name: Polaris Security Scan

on:
  push:
    branches:
      - main
      - master
      - develop
      - stage
      - release

  pull_request:
    branches:
      - main
      - master
      - develop
      - stage
      - release

  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  polaris:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v5

      - name: Debug Variables
        run: |
          echo "POLARIS_URL='${{ vars.POLARIS_URL }}'"

      - name: Call Pre-Scan API
        run: |
          curl -X POST \
            "https://<polaris-url>/api/portfolios/<portfolioId>/applications/<applicationId>/projects/<projectId>/branches" \
            -H "accept: application/vnd.polaris.portfolios.branches-1+json" \
            -H "Api-Token: ${{ secrets.POLARIS_ACCESS_TOKEN }}" \
            -H "Content-Type: application/vnd.polaris.portfolios.branches-1+json" \
            -H "X-Client-Source: dev-portal" \
            -d '{
              "name": "main",
              "source": "CI",
              "isDefault": false
            }'

      - name: Polaris Security Scan
        id: polaris-scan
        uses: blackduck-inc/black-duck-security-scan@v2

        with:
          # Required
          polaris_server_url: ${{ vars.POLARIS_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}

          # Assessment Types
          polaris_assessment_types: SAST
          polaris_test_sast_type: SAST-RAPID

          # Scan Locations
          polaris_test_sast_location: hybrid
          polaris_test_sca_location: hybrid

          # Diagnostics
          include_diagnostics: true

          # GitHub Integration
          github_token: ${{ secrets.GITHUB_TOKEN }}
          polaris_prComment_enabled: true

          # Fix PR Creation
          polaris_fixpr_enabled: true

          # External Issues
          polaris_externalIssues_create: true

          # SARIF Report
          polaris_reports_sarif_create: true

          # Optional
          # mark_build_status: failure
          # polaris_prComment_enabled: false
